version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tracker:/app/tracker
    command: poetry run uvicorn tracker.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./tracker/.env
    ports:
      - 8000:8000
